WITH 
FG AS (
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
),
SG AS(
    SELECT ED.ID, ED.PARENT_ID
    FROM ECOLI_DATA ED 
    JOIN FG ON ED.PARENT_ID = FG.ID
)
SELECT ED.ID
FROM ECOLI_DATA ED 
JOIN SG ON ED.PARENT_ID = SG.ID
ORDER BY ED.ID