# IFNULL 미사용
WITH CTE AS (
    SELECT 
        CASE WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH 
    END AS LENGTH
    FROM FISH_INFO
)

SELECT ROUND(AVG(LENGTH), 2) AS AVERAGE_LENGTH
FROM CTE

# IFNULL 사용
SELECT ROUND(AVG(IFNULL(LENGTH, 10)), 2) AS AVERAGE_LENGTH
FROM FISH_INFO
