-- 코드를 입력하세요
SELECT DISTINCT C.CAR_ID, C.CAR_TYPE,
ROUND(30 * C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY R ON C.CAR_ID = R.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ('SUV', '세단')
AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                     WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
AND DURATION_TYPE = '30일 이상'
AND (30 * C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100) >= 500000 
AND (30 * C.DAILY_FEE * (100 - D.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;