# NTILE() - PARTITION을 지정된 수 만큼의 등급으로 나누어 각 등급 번호를 출력
SELECT ID, 
(CASE
 # 정렬 순서에 따라 등급 번호 순서 바뀜
  WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 1 THEN 'LOW'
  WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 2 THEN 'MEDIUM'
  WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) = 3 THEN 'HIGH'
  ELSE 'CRITICAL' END) AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID;

/*
WITH 
Percentage AS 
(SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS SIZE_GROUP
FROM ECOLI_DATA),

ColonyNames AS 
(SELECT ID,
    CASE WHEN SIZE_GROUP = 1 THEN 'CRITICAL'
        WHEN SIZE_GROUP = 2 THEN 'HIGH'
        WHEN SIZE_GROUP = 3 THEN 'MEDIUM'
        WHEN SIZE_GROUP = 4 THEN 'LOW'
    END AS COLONY_NAME 
    FROM Percentage)
    
SELECT ED.ID, CN.COLONY_NAME
FROM ECOLI_DATA ED
INNER JOIN ColonyNames CN 
ON ED.ID = CN.ID
ORDER BY ED.ID;
*/

# https://velog.io/@zoo33/SQL-%EC%88%9C%EC%9C%84%ED%95%A8%EC%88%98
# https://jaimemin.tistory.com/2466