WITH RECURSIVE CTE AS (
    SELECT D1.ID AS ID, D2.ID AS CHILD_ID, 1 AS LEVEL
    FROM ECOLI_DATA D1
    LEFT OUTER JOIN ECOLI_DATA D2
    ON D1.ID = D2.PARENT_ID
    WHERE D1.PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT D1.CHILD_ID AS ID, D2.ID AS CHILD_ID, LEVEL + 1 AS LEVEL
    FROM CTE D1
    LEFT OUTER JOIN ECOLI_DATA D2
    ON D1.CHILD_ID = D2.PARENT_ID
    WHERE D1.CHILD_ID IS NOT NULL
)

# ID 중복 제거 필수
SELECT COUNT(DISTINCT(ID)) AS COUNT, LEVEL AS GENERATION
FROM CTE
WHERE CHILD_ID IS NULL # 자식이 없는 대장균
GROUP BY LEVEL