-- 코드를 입력하세요
WITH VALUE AS (
    SELECT C.DAILY_FEE, C.CAR_TYPE, H.HISTORY_ID,
           DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        ELSE 'NONE' END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C 
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT VALUE.HISTORY_ID, 
       ROUND(VALUE.DAILY_FEE * VALUE.PERIOD 
             * (100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM VALUE
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON VALUE.DURATION_TYPE = D.DURATION_TYPE
AND VALUE.CAR_TYPE = D.CAR_TYPE
ORDER BY FEE DESC, VALUE.HISTORY_ID DESC;