-- 코드를 입력하세요
SELECT J.FLAVOR
FROM FIRST_HALF F JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
                        FROM JULY GROUP BY FLAVOR) J
ON F.FLAVOR = J.FLAVOR
ORDER BY J.TOTAL_ORDER + F.TOTAL_ORDER DESC
LIMIT 3;