# 1. FISH_TYPE으로 그룹화하며 그룹별로 가장 큰 LENGTH 추출
# 2. 3가지 테이블 모두 조인하여 출력형식에 맞게 출력

SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE) C
ON B.FISH_TYPE = C.FISH_TYPE AND A.LENGTH = C.LENGTH
ORDER BY ID