# 내 풀이
SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E
JOIN (SELECT EMP_NO,
      SUM(SCORE) AS SCORE
      FROM HR_GRADE
      GROUP BY EMP_NO) G
ON E.EMP_NO = G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1

# 다른 풀이
SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES E, HR_GRADE G
WHERE E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY SUM(SCORE) DESC
LIMIT 1
